# Generated by Django 5.2.10 on 2026-01-08 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_ns', models.FloatField(verbose_name='Länge Nord/Süd [m]')),
                ('width_ow', models.FloatField(verbose_name='Breite Ost/West [m]')),
                ('storeys', models.IntegerField(verbose_name='Geschosse')),
                ('room_height', models.FloatField(verbose_name='Raumhöhe [m]')),
                ('u_wall', models.FloatField(verbose_name='U-Wert Außenwand [W/m²K]')),
                ('u_roof', models.FloatField(verbose_name='U-Wert Dach [W/m²K]')),
                ('u_floor', models.FloatField(verbose_name='U-Wert Kellerdecke [W/m²K]')),
                ('u_window', models.FloatField(verbose_name='U-Wert Fenster [W/m²K]')),
                ('window_share_n', models.FloatField(default=50, verbose_name='Fensteranteil Nord [%]')),
                ('window_share_e', models.FloatField(default=50, verbose_name='Fensteranteil Ost [%]')),
                ('window_share_s', models.FloatField(default=50, verbose_name='Fensteranteil Süd [%]')),
                ('window_share_w', models.FloatField(default=50, verbose_name='Fensteranteil West [%]')),
                ('g_n', models.FloatField(default=0.6, verbose_name='g-Wert Nord')),
                ('g_e', models.FloatField(default=0.6, verbose_name='g-Wert Ost')),
                ('g_s', models.FloatField(default=0.6, verbose_name='g-Wert Süd')),
                ('g_w', models.FloatField(default=0.6, verbose_name='g-Wert West')),
                ('person_density', models.FloatField(default=20, verbose_name='Personendichte [m²/Person]')),
                ('persons', models.IntegerField(default=24, verbose_name='Personen')),
                ('air_change_rate', models.FloatField(default=0.5, verbose_name='Luftwechselrate n [1/h]')),
                ('degree_days', models.FloatField(default=3000, verbose_name='Heizgradtage HDD [K*d]')),
                ('pv_roof_share', models.FloatField(default=50, verbose_name='PV-Anteil Dachfläche [%]')),
                ('pv_specific_yield', models.FloatField(default=180, verbose_name='PV-spezifischer Ertrag [kWh/m²*a]')),
                ('pv_self_consumption_share', models.FloatField(default=70, verbose_name='PV-Eigenverbrauchsanteil [%]')),
                ('setpoint_temp', models.FloatField(verbose_name='Solltemperatur [°C]')),
                ('result_Q_T', models.FloatField(blank=True, null=True)),
                ('result_Q_V', models.FloatField(blank=True, null=True)),
                ('result_Q_I', models.FloatField(blank=True, null=True)),
                ('result_Q_S', models.FloatField(blank=True, null=True)),
                ('result_Q_h', models.FloatField(blank=True, null=True)),
                ('result_H_T', models.FloatField(blank=True, null=True)),
                ('result_H_V', models.FloatField(blank=True, null=True)),
                ('result_floor_area', models.FloatField(blank=True, null=True)),
                ('result_roof_area', models.FloatField(blank=True, null=True)),
                ('result_opaque_wall_area', models.FloatField(blank=True, null=True)),
                ('result_window_area', models.FloatField(blank=True, null=True)),
                ('result_Q_S_n', models.FloatField(blank=True, null=True)),
                ('result_Q_S_e', models.FloatField(blank=True, null=True)),
                ('result_Q_S_s', models.FloatField(blank=True, null=True)),
                ('result_Q_S_w', models.FloatField(blank=True, null=True)),
                ('result_Q_PV_total', models.FloatField(blank=True, null=True)),
                ('result_Q_PV_on', models.FloatField(blank=True, null=True)),
                ('result_Q_PV_off', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvelopeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('use_custom_layers', models.BooleanField(default=True, help_text='Falls deaktiviert, wird ein vorgegebener U-Wert genutzt.')),
                ('u_value_external', models.FloatField(blank=True, help_text='Falls vorhanden, extern vorgegebener U-Wert', null=True)),
                ('u_value_calculated', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GwpManufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_components_gwp', models.FloatField(default=0, verbose_name='Herstellung neue Bauteile [kg]')),
                ('existing_components_gwp', models.FloatField(default=0, verbose_name='Herstellung Bestandsbauteile [kg]')),
                ('service_life_years', models.FloatField(default=50, verbose_name='Nutzungsdauer [a]')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gwp_manufacturing', to='energyapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='GwpCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_district_regen_kwh', models.FloatField(default=0, verbose_name='Fernwärme regenerativ [kWh/a]')),
                ('heat_district_avg_kwh', models.FloatField(default=0, verbose_name='Fernwärme durchschnitt [kWh/a]')),
                ('gas_kwh', models.FloatField(default=0, verbose_name='Gas [kWh/a]')),
                ('electricity_kwh', models.FloatField(default=0, verbose_name='Strom [kWh/a]')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gwp_compensation', to='energyapp.building')),
                ('manufacturing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='energyapp.gwpmanufacturing')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.CharField(choices=[('inside', 'Innen'), ('layer', 'Materialschicht'), ('outside', 'Außen')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('thickness', models.FloatField(blank=True, help_text='d in m', null=True)),
                ('lambda_value', models.FloatField(blank=True, help_text='λ in W/mK', null=True)),
                ('R_value', models.FloatField(blank=True, help_text='Widerstand R', null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='energyapp.envelopeelement')),
            ],
        ),
        migrations.CreateModel(
            name='SummerProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sommerlicher Wärmeschutz', help_text="Name des Szenarios (z.B. 'Standard Sommerfall').", max_length=100)),
                ('orientation', models.CharField(choices=[('N', 'Nord'), ('E', 'Ost'), ('S', 'Süd'), ('W', 'West')], default='S', max_length=1, verbose_name='Fassadenorientierung (kritischer Raum)')),
                ('ngf_m2', models.FloatField(default=30.0, verbose_name='Nettogrundfläche Raum (NGF) [m²]')),
                ('window_area_m2', models.FloatField(default=0.0, verbose_name='Fensterfläche (kritischer Raum) [m²]')),
                ('glazing_category', models.CharField(choices=[('double', 'zweifach'), ('triple', 'dreifach'), ('solar', 'Sonnenschutzglas (g ≤ 0.40)')], default='double', max_length=20, verbose_name='Verglasungskategorie')),
                ('shading_type', models.CharField(choices=[('none', 'ohne Sonnenschutz'), ('internal', 'innenliegend / zwischen Scheiben'), ('roller_closed', 'Rollladen geschlossen'), ('jalousie_45', 'Jalousie 45°'), ('awning', 'Markise'), ('overhang', 'Vordach / Überhang')], default='none', max_length=30, verbose_name='Sonnenschutztyp (kritischer Raum)')),
                ('climate_region', models.CharField(choices=[('A', 'Klimaregion A'), ('B', 'Klimaregion B'), ('C', 'Klimaregion C')], default='B', max_length=1, verbose_name='Klimaregion')),
                ('night_ventilation', models.CharField(choices=[('none', 'keine'), ('slight', 'erhöht leicht'), ('strong', 'erhöht stark')], default='none', max_length=10, verbose_name='Nachtlüftung')),
                ('passive_cooling', models.BooleanField(default=False, verbose_name='Passive Kühlung vorhanden')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_protections', to='energyapp.building')),
            ],
        ),
    ]
