# Generated by Django 5.2.10 on 2026-01-08 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwpmanufacturing',
            name='existing_components_gwp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Herstellung Bestandsbauteile [kg]'),
        ),
        migrations.AlterField(
            model_name='gwpmanufacturing',
            name='new_components_gwp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Herstellung neue Bauteile [kg]'),
        ),
        migrations.AlterField(
            model_name='gwpmanufacturing',
            name='service_life_years',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nutzungsdauer [a]'),
        ),
    ]
