# Generated by Django 5.2.10 on 2026-01-08 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0002_alter_gwpmanufacturing_existing_components_gwp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwpmanufacturing',
            name='existing_components_gwp',
        ),
        migrations.RemoveField(
            model_name='gwpmanufacturing',
            name='new_components_gwp',
        ),
        migrations.AddField(
            model_name='gwpmanufacturing',
            name='kg300_existing',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KG300 Bestandsbauteile [kg]'),
        ),
        migrations.AddField(
            model_name='gwpmanufacturing',
            name='kg300_new',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KG300 neue Bauteile [kg]'),
        ),
        migrations.AddField(
            model_name='gwpmanufacturing',
            name='kg400_existing',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KG400 Bestandsbauteile [kg]'),
        ),
        migrations.AddField(
            model_name='gwpmanufacturing',
            name='kg400_new',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KG400 neue Bauteile [kg]'),
        ),
    ]
