# Generated by Django 5.2.10 on 2026-01-08 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapp', '0003_remove_gwpmanufacturing_existing_components_gwp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwpcompensation',
            name='manufacturing',
        ),
        migrations.AddField(
            model_name='gwpcompensation',
            name='factor_electricity',
            field=models.FloatField(default=0.3538, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO₂-Faktor Strom [kg/kWh]'),
        ),
        migrations.AddField(
            model_name='gwpcompensation',
            name='factor_gas',
            field=models.FloatField(default=0.201, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO₂-Faktor Gas [kg/kWh]'),
        ),
        migrations.AddField(
            model_name='gwpcompensation',
            name='factor_heat_avg',
            field=models.FloatField(default=0.28, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO₂-Faktor Fernwärme durchschnitt [kg/kWh]'),
        ),
        migrations.AddField(
            model_name='gwpcompensation',
            name='factor_heat_regen',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO₂-Faktor Fernwärme regenerativ [kg/kWh]'),
        ),
        migrations.AlterField(
            model_name='gwpcompensation',
            name='electricity_kwh',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Strom [kWh/a]'),
        ),
        migrations.AlterField(
            model_name='gwpcompensation',
            name='gas_kwh',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gas [kWh/a]'),
        ),
        migrations.AlterField(
            model_name='gwpcompensation',
            name='heat_district_avg_kwh',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fernwärme durchschnitt [kWh/a]'),
        ),
        migrations.AlterField(
            model_name='gwpcompensation',
            name='heat_district_regen_kwh',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fernwärme regenerativ [kWh/a]'),
        ),
    ]
